import { OpenAI } from 'openai';
import { Prisma } from '@prisma/client';
import { prisma } from '@/lib/prisma';

type TranslationPassage = {
  version_code: string;
  version_name: string;
  public_domain: boolean;
  license_notes: string | null;
  reference: string;
  text: string;
};

/**
 * Translation intelligence must never fabricate or paraphrase text while
 * presenting it as a named Bible translation. Named translation text comes
 * only from enabled local/public-domain passages or configured licensed
 * provider data that has already been persisted in scripture_passages.
 */
export class TranslationIntelligenceEngine {
  async getVerseWithAllTranslations(reference: string) {
    const normalizedReference = reference.trim();
    if (!normalizedReference) return null;

    const passages = await prisma.$queryRaw<TranslationPassage[]>(Prisma.sql`
      SELECT
        p.version_code,
        v.name AS version_name,
        v.public_domain,
        v.license_notes,
        p.reference,
        p.text
      FROM scripture_passages p
      JOIN bible_versions v ON v.code = p.version_code
      LEFT JOIN bible_translation_providers provider ON provider.id = v.provider_id
      WHERE p.reference ILIKE ${normalizedReference}
        AND v.enabled = true
        AND (
          v.public_domain = true
          OR (provider.id IS NOT NULL AND provider.enabled = true)
        )
      ORDER BY v.public_domain DESC, v.name ASC
      LIMIT 16
    `);

    if (!passages.length) return null;

    const translations = passages.reduce<Record<string, { name: string; text: string; publicDomain: boolean; licenseNotes: string | null }>>(
      (acc, passage) => {
        acc[passage.version_code] = {
          name: passage.version_name,
          text: passage.text,
          publicDomain: passage.public_domain,
          licenseNotes: passage.license_notes,
        };
        return acc;
      },
      {},
    );

    return {
      reference: passages[0].reference,
      translations,
      comparison: await this.createComparisonInsight(passages),
      licensingNote:
        'Named Bible text is returned only from enabled public-domain content or configured licensed providers. AI never invents text and labels it as a published translation.',
    };
  }

  private async createComparisonInsight(passages: TranslationPassage[]) {
    if (!process.env.OPENAI_API_KEY || passages.length < 2) {
      return 'Compare wording, emphasis, and readability across the available licensed or public-domain texts. Translation text itself is never generated by AI.';
    }

    try {
      const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
      const response = await openai.chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content:
              'You explain differences between Bible translations supplied by the application. Never rewrite, reconstruct, or claim missing translation text. Do not claim divine revelation or prophecy. Return JSON with a comparison field containing a concise pastoral-study explanation.',
          },
          {
            role: 'user',
            content: JSON.stringify(
              passages.map((passage) => ({
                version: passage.version_code,
                reference: passage.reference,
                text: passage.text,
              })),
            ),
          },
        ],
        response_format: { type: 'json_object' },
        temperature: 0.2,
      });

      const parsed = JSON.parse(response.choices[0]?.message?.content || '{}');
      return typeof parsed.comparison === 'string'
        ? parsed.comparison
        : 'Review the supplied translations side-by-side, noting wording and emphasis while keeping the passage in context.';
    } catch (error) {
      console.error('Translation comparison insight failed:', error);
      return 'Review the supplied translations side-by-side, noting wording and emphasis while keeping the passage in context.';
    }
  }
}
