import { Mux } from '@mux/mux-node';
import { Sermon } from '@prisma/client';

const mux = new Mux({
    tokenId: process.env.MUX_TOKEN_ID || 'dummy_mux_id',
    tokenSecret: process.env.MUX_TOKEN_SECRET || 'dummy_mux_secret',
});

export class VideoHostingService {
    async uploadSermon(fileUrl: string, sermon: Sermon) {
        try {
            const asset = await mux.video.assets.create({
                inputs: [{ url: fileUrl }],
                playback_policy: ['public'],
                mp4_support: 'standard',
                master_access: 'temporary',
            });

            // We'd store this in prisma under a 'Video' model
            return {
                sermonId: sermon.id,
                assetId: asset.id,
                playbackUrl: asset.playback_ids && asset.playback_ids.length > 0
                    ? `https://stream.mux.com/${asset.playback_ids[0].id}.m3u8`
                    : '',
                thumbnailUrl: asset.playback_ids && asset.playback_ids.length > 0
                    ? `https://image.mux.com/${asset.playback_ids[0].id}/thumbnail.jpg`
                    : '',
                status: 'processing'
            };
        } catch (e) {
            console.warn("Video upload simulated:", e);
            return {
                playbackUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
                thumbnailUrl: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3',
                status: 'simulated'
            };
        }
    }

    async processWithAI(videoDetails: any) {
        // Simulated AI processing for generating chapters and key moments
        return {
            chapters: [
                { time: 0, title: 'Introduction' },
                { time: 300, title: 'The Core Message' },
                { time: 1200, title: 'Altar Call' }
            ],
            keyMoments: [
                { start: 300, end: 340, description: 'Powerful revelation on grace' }
            ],
            highlights: [
                { id: 'h1', duration: 45, clipUrl: '' } // To be generated by generateClips
            ]
        };
    }

    async generateClips(assetId: string, moments: Array<{ start: number; end: number }>) {
        try {
            const clips = await Promise.all(moments.map(async (moment) => {
                const clip = await mux.video.assets.create({
                    inputs: [
                        {
                            url: `mux://assets/${assetId}`,
                            start_time: moment.start,
                            end_time: moment.end,
                        },
                    ],
                    playback_policy: ['public'],
                });

                return {
                    url: clip.playback_ids ? `https://stream.mux.com/${clip.playback_ids[0].id}.m3u8` : '',
                    start: moment.start,
                    end: moment.end,
                };
            }));
            return clips;
        } catch (e) {
            return [{ url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8', start: 0, end: 15 }];
        }
    }
}
