#!/usr/bin/env bash
# Idempotent repository bootstrap for Digital Church OS Cloud Agents.
#
# Runs after the repository is checked out. Safe to run repeatedly:
#   - installs node dependencies (postinstall generates the Prisma client)
#   - ensures a local PostgreSQL cluster + database exist
#   - syncs the Prisma schema
#   - seeds baseline data (admin user + religion/AI modules) without duplicating
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "[setup] repo root: $REPO_ROOT"

# 1. Local dev env file (non-secret). Never clobber an existing .env (may hold real secrets).
if [ ! -f .env ]; then
  cp .cursor/dev.env .env
  echo "[setup] created .env from .cursor/dev.env"
else
  echo "[setup] .env already present; leaving it untouched"
fi

# 2. Node dependencies (package.json postinstall runs `prisma generate`).
echo "[setup] installing node dependencies"
npm ci

# 3. Ensure PostgreSQL is installed, running, and provisioned.
bash .cursor/postgres.sh ensure

# 4. Sync the Prisma schema to the database (client already generated by postinstall).
echo "[setup] syncing Prisma schema"
npx prisma db push --skip-generate

# 5. Seed baseline data.
DB_URL="postgresql://postgres:password@localhost:5432/digital_church_os"

# Admin login (upsert -> idempotent).
echo "[setup] seeding admin user"
npx tsx scripts/seed-admin.ts

# Religion + AI modules. prisma/seed.ts uses create() for modules, so only run
# it when none exist to keep this step idempotent.
MODULE_COUNT="$(PGPASSWORD=password psql "$DB_URL" -tAc 'SELECT COUNT(*) FROM "AIModule";' 2>/dev/null | tr -d '[:space:]' || echo 0)"
if [ "${MODULE_COUNT:-0}" = "0" ]; then
  echo "[setup] seeding religion + AI modules"
  npx tsx prisma/seed.ts
else
  echo "[setup] AI modules already present (${MODULE_COUNT}); skipping base seed"
fi

echo "[setup] done"
